#!/bin/bash
# try to run the `main' program and see if any exception happens

if [ $# -lt 1 ];then
	echo "Usage: ./batch benchmark"
	exit 1
fi

FILENAME="$1"
OUTNAME="$FILENAME".result
if [ ! -f "$FILENAME" ];then
	echo "File not exist!"
	exit 1
fi
NUMSUBPROBLEMS=`awk '/NUMSUBPROBLEMS/ {print $2;}' "$FILENAME"`
if [ -z "$NUMSUBPROBLEMS" ];then
	echo "Error, subproblem num incorrect!"
	exit 1
fi

echo running "$FILENAME", subproblem count = "$NUMSUBPROBLEMS"
echo output to "$OUTNAME"
echo -n > "$OUTNAME"

# column1 = cell used , column2 = run time
time ./debug "$FILENAME" > check 2>&1 
cat check | awk '/used/ {printf("%d ",$6)} /max / {printf("%d\n",$4)}' > "$OUTNAME"
exit 0
