#!/bin/bash
# given a droplet routing benchmark name
# generate a tex file visulizes all the subproblems
# REQUIRE: 
# 1.parser is in the current directory
# 2.result_header.tex in the current directory

NAME=$1
./parser $NAME
cat draw_subproblem_header.tex > "${NAME}.tex"
NUM=`ls ${NAME}_p* | wc -l`
for i in `seq 1 $NUM`
do
	cat ${1}_p${i}.tex >> "${NAME}.tex"
done
echo "\\end{document}" >> "${NAME}.tex"
rm ${NAME}_p*

exit 0
